### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by JesusChapman** [rsanjuan87/Termux-DialerGUI#1]
Hello, I've been fascinated by your project 
![Screenshot_20210510-170627](https://user-images.githubusercontent.com/64093255/117730576-2cde6700-b1b2-11eb-81de-1d54728b1677.png) 
I use termux-desktop-xfce, a desktop that I recently created for termux, and I have an apt-repo with debs packages for it, I would like to create a deb package of your project, of course, if you allow me, obviously I will leave credits to you, 
A and I have a project, in which I would very much like you to help me

**Comment by rsanjuan87** [comment]
Hello
of course you Can
 In fact I am honored and the project was made to share with everyone

**Comment by JesusChapman** [comment]
Super, I appreciate it, I already made a deb package and uploaded it to my repository, you can install it with pkg install, a and I see you use openbox, I have a different project : 

https://github.com/Yisus7u7/termux-desktop-xfce

I was dedicated a lot of time and I would like you to join, if you want...

**Comment by JesusChapman** [comment]
If you want to join my little project write me to my WhatsApp :   

+57 3006748497

**Comment by rsanjuan87** [comment]
I loved your desktop project. It's looks very nice
I don't have a WhatsApp
[http://t.me/rsanjuan87](http://t.me/rsanjuan87)
You can contact me on Telegram

**Comment by JesusChapman** [comment]
Okey
